"""
Django settings for Myadmin project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from datetime import timedelta
from corsheaders.defaults import default_headers
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o_sw40i2b$ln0p#oq=9a@zez&g$_^+njs-$@8bb2uq*x#(qe4w'




# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'Enter JWT token as: Bearer <your_token>'
        }
    },
    'SECURITY_REQUIREMENTS': [{'Bearer': []}],
}




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # 'rest_framework.authtoken',
    # 'Myadmin.User',
    'drf_yasg',
    'corsheaders',
    'AdminApp',    
    'User',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # corsheader middleware
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# session 


ROOT_URLCONF = 'Myadmin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=5),  # Access token valid for  hours
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Refresh token valid for 7 days
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}


REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "AdminApp.pagination.CustomPagination",
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}



WSGI_APPLICATION = 'Myadmin.wsgi.application'

AUTH_USER_MODEL = 'User.User_Master'

CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']


# For testing only: allow all origins
CORS_ALLOW_ALL_ORIGINS = True   

# Optional: allow credentials (needed if using CSRF)
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [

    "http://localhost:3001",

    "http://192.168.29.213:8000",
    
    "http://localhost:5173",
    
    "http://192.168.29.213:5173",
    
    "https://e6f913326811.ngrok-free.app",

    ] 

CORS_ALLOW_HEADERS = [  
    'content-type',
    'authorization',
    'session-key',  
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "session-key",
]

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

#postgresql database connection 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'myadmin_db',         # Your database name
        'USER': 'postgres',       # The database user
        'PASSWORD': 'postgres',      # The database user password
        'HOST': '127.0.0.1',          # Localhost
        'PORT': '5432',               # Default PostgreSQL port
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
print("MEDIA_ROOT =", MEDIA_ROOT)
print("MEDIA_URL =", MEDIA_URL)


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'vauchapp@gmail.com'
EMAIL_HOST_PASSWORD = 'hbhpuncysawweloa'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False


# NIN API Calling
USE_NIN_MOCK = False

NIN_BASE_URL = "https://api.dojah.io/api/v1/kyc/nin"  


DOJAH_ENVIRONMENT = "sandbox" 

DOJAH_BASE_URLS = {
    "sandbox": "https://sandbox.dojah.io",
    "production": "https://api.dojah.io"
}

# CAC API Calling
APP_ID = "68e604c2fbacfbd6a0103a49"

SANDBOX_SECRETE_KEY="test_sk_schiSmtfj5HjoCRWZuG08Tdes"

PRODUCTION_SECRET_KEY = "prod_sk_cGof8z2nMFcB2l3TNVuWXpeO3"

USE_CAC_MOCK = False

CAC_BASE_URL = "https://api.dojah.io/api/v1/kyc/cac/advance"


# number plate 

QOREID_BASE_URL = "https://api.qoreid.com"

## QoreID Test Account Credentials

# QOREID_CLIENT_ID = "U6FE4PXQ9WO5DKMGYHSP"

# QOREID_SECRET = "c11ea00116f248d88bcb1d8bc17c4035"

QOREID_CLIENT_ID = "YDFHJDY2YI0F9DKFM983"

QOREID_SECRET = "efa7147b1e794a4bba0dff1ac2673321"

ORDER_PROCESSING_TIME = 60

GOOGLE_MAPS_API_KEY = "AIzaSyDe3Fn7XfwCluxbKnZz_YwXpMY8Y9INcOA"

SET_KM_PRICE = 150

MICRO_INSURANCE = 0

OWNER_COMMISSION_RATE = 0.70

AGENCY_COMMISSION_RATE = 0.10