# Generated by Django 4.2.24 on 2025-12-12 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTempUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('phone_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('otp', models.CharField(max_length=6, null=True)),
                ('otp_time_limit', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_temp_user',
            },
        ),
        migrations.CreateModel(
            name='CancellationReasonMaster',
            fields=[
                ('cancellation_reason_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cancellation Reason',
                'verbose_name_plural': 'Cancellation Reason Master',
                'db_table': 'cancellation_reason_master',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceStatusMaster',
            fields=[
                ('invoice_status_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_status_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice Status',
                'verbose_name_plural': 'Invoice Status Master',
                'db_table': 'invoice_status_master',
            },
        ),
        migrations.CreateModel(
            name='Lease_Agency_Master',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agency_profile', models.ImageField(blank=True, null=True, upload_to='lease/')),
                ('cac_number', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('business_name', models.CharField(max_length=255)),
                ('business_Email', models.EmailField(max_length=254)),
                ('business_number', models.BigIntegerField()),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.BigIntegerField()),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Lease_Agency_Master',
            },
        ),
        migrations.CreateModel(
            name='LeaseInvoice',
            fields=[
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('micro_insurance', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='User.invoicestatusmaster')),
            ],
            options={
                'verbose_name': 'Lease Invoice',
                'verbose_name_plural': 'Lease Invoices',
                'db_table': 'lease_invoice',
            },
        ),
        migrations.CreateModel(
            name='LeaseOrderMaster',
            fields=[
                ('lease_order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('purpose', models.CharField(max_length=150)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('lease_type', models.CharField(choices=[('chauffeur', 'chauffeur'), ('self_drive', 'self_drive')], default='self_drive', max_length=50)),
                ('leased_for', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField()),
                ('client_location', models.CharField(max_length=255)),
                ('delivery_address', models.TextField()),
                ('delivery_distance_km', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('estimated_delivery_cost', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('remaining_time', models.DateTimeField(blank=True, null=True)),
                ('no_of_passenger', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_orders', to='User.lease_agency_master')),
                ('cancellation_reason', models.ForeignKey(blank=True, db_column='cancellation_reason_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.cancellationreasonmaster')),
            ],
            options={
                'verbose_name': 'Lease Order',
                'verbose_name_plural': 'Lease Order Master',
                'db_table': 'lease_order_master',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_status_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Status Master',
                'db_table': 'order_status_master',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodMaster',
            fields=[
                ('payment_method_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Method Master',
                'db_table': 'payment_method_master',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatusMaster',
            fields=[
                ('payment_status_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_status_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Status',
                'verbose_name_plural': 'Payment Status Master',
                'db_table': 'payment_status_master',
            },
        ),
        migrations.CreateModel(
            name='PolicyMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Policy_Master',
            },
        ),
        migrations.CreateModel(
            name='SetCommissionMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_name', models.CharField(max_length=150, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Set_Commission_Master',
            },
        ),
        migrations.CreateModel(
            name='User_Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'User_Type',
            },
        ),
        migrations.CreateModel(
            name='VehicleStatusMaster',
            fields=[
                ('vehicle_status_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_status_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Status',
                'verbose_name_plural': 'Vehicle Status Master',
                'db_table': 'vehicle_status_master',
            },
        ),
        migrations.CreateModel(
            name='User_Master',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('nin_number', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('middle_name', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.BigIntegerField()),
                ('employment_status', models.CharField(max_length=150, null=True)),
                ('marital_status', models.CharField(max_length=150, null=True)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Active', max_length=10)),
                ('raw_api_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user_type')),
            ],
            options={
                'db_table': 'User_Master',
            },
        ),
        migrations.CreateModel(
            name='Vehicle_Owner_Master',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cac_number', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('business_name', models.CharField(max_length=255)),
                ('business_Email', models.EmailField(max_length=254)),
                ('business_number', models.BigIntegerField()),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.BigIntegerField()),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('name_of_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.BigIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.lease_agency_master')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Vehicle_Owner_Master',
            },
        ),
        migrations.CreateModel(
            name='Vehicle_Owner_Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='User.vehicle_owner_master')),
            ],
            options={
                'db_table': 'Vehicle_Owner_Driver',
            },
        ),
        migrations.CreateModel(
            name='Vehicle_Owner_Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.lease_agency_master')),
                ('vehicle_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.vehicle_owner_master')),
            ],
            options={
                'db_table': 'Vehicle_Owner_Agency',
            },
        ),
        migrations.CreateModel(
            name='Vehicle_Master',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registered_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('plate_number', models.CharField(max_length=100)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('body_type', models.CharField(max_length=100)),
                ('mfg_year', models.PositiveIntegerField()),
                ('vehicle_identify_number', models.CharField(max_length=100)),
                ('license_renewed_date', models.DateField(blank=True, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('insurance_renewed_date', models.DateField(blank=True, null=True)),
                ('insurance_expiry_date', models.DateField(blank=True, null=True)),
                ('road_worthiness_cert_date', models.DateField(blank=True, null=True)),
                ('road_worthiness_expiry_date', models.DateField(blank=True, null=True)),
                ('engine_spec', models.TextField(blank=True, null=True)),
                ('other_spec', models.TextField(blank=True, null=True)),
                ('primary_location', models.CharField(max_length=255)),
                ('lease_price_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('passenger_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='User.vehicle_owner_master')),
                ('vehicle_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='User.vehiclestatusmaster')),
            ],
            options={
                'db_table': 'Vehicle',
            },
        ),
        migrations.CreateModel(
            name='Vehicle_Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='User.vehicle_master')),
            ],
            options={
                'db_table': 'Vehicle_Image',
            },
        ),
        migrations.CreateModel(
            name='Vehicle_Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.lease_agency_master')),
                ('vehicle_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_agencies', to='User.vehicle_master')),
            ],
            options={
                'db_table': 'User_vehicle_agency',
            },
        ),
        migrations.CreateModel(
            name='User_OTP_Master',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=6, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_otp_master',
            },
        ),
        migrations.CreateModel(
            name='PaymentMaster',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(blank=True, max_length=150, null=True)),
                ('payment_ref', models.CharField(max_length=150, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='User.leaseinvoice')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='User.paymentmethodmaster')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='User.paymentstatusmaster')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payment Master',
                'db_table': 'payment_master',
            },
        ),
        migrations.CreateModel(
            name='LeaseReviewMaster',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='User.leaseordermaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lease Review',
                'verbose_name_plural': 'Lease Review Master',
                'db_table': 'lease_review_master',
            },
        ),
        migrations.AddField(
            model_name='leaseordermaster',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeur_orders', to='User.vehicle_owner_driver'),
        ),
        migrations.AddField(
            model_name='leaseordermaster',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_orders', to='User.orderstatusmaster'),
        ),
        migrations.AddField(
            model_name='leaseordermaster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaseordermaster',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_orders', to='User.vehicle_master'),
        ),
        migrations.AddField(
            model_name='leaseinvoice',
            name='lease_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='User.leaseordermaster'),
        ),
        migrations.AddField(
            model_name='lease_agency_master',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('ip_address', models.GenericIPAddressField()),
                ('expire_date', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custome_session',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_infos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact_info',
            },
        ),
        migrations.CreateModel(
            name='AdminLoginOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=6, null=True)),
                ('otp_time_limit', models.DateTimeField(blank=True, null=True)),
                ('created_at_otp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Login_otp',
            },
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('Profile_Update', 'Profile_Update')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_activity_log',
            },
        ),
    ]
