# Generated by Django 4.2.24 on 2025-12-15 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePriceMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_make', models.CharField(max_length=128)),
                ('vehicle_model', models.CharField(max_length=128)),
                ('vehicle_class', models.CharField(blank=True, max_length=64, null=True)),
                ('vehicle_location', models.CharField(blank=True, max_length=128, null=True)),
                ('vehicle_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lease_per_day', models.IntegerField()),
                ('delivery_rate_per_km', models.IntegerField(blank=True, null=True)),
                ('micro_insurance_rate_per_rider', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Price Matrix',
                'verbose_name_plural': 'Vehicle Price Matrix Records',
                'db_table': 'vehicle_price_matrix',
            },
        ),
        migrations.AlterField(
            model_name='vehicle_agency',
            name='status',
            field=models.CharField(choices=[('Deactive', 'Deactive'), ('Active', 'Active')], max_length=50),
        ),
    ]
